qlib_init:
    provider_uri: "D:/studystudy/Course/Postgraduate/M1/Quant/project/qlib_framework/data/cn_data"
    region: cn

market: &market [SH600000, SZ000001, SH600519]

data_handler_config: &data_handler_config
    start_time: 2020-01-01
    end_time: 2020-03-31
    instruments: *market
    data_loader:
        class: QlibDataLoader
        module_path: qlib.data.dataset.loader
        kwargs:
            config:
                feature:
                    - ["$open", "$high", "$low", "$close", "$volume", "$amount", "$turn", "$return", "$factor", "($close - $open) / $open", "($high - $low) / Ref($close, 1)", "$close / Ref($close, 1) - 1"]
                    - ["OPEN", "HIGH", "LOW", "CLOSE", "VOLUME", "AMOUNT", "TURN", "RET", "FACTOR", "INTRADAY_RET", "RANGE_PREV_CLOSE", "RET_1D"]
                label:
                    - ["Ref($close, -2) / Ref($close, -1) - 1"]
                    - ["LABEL0"]
    infer_processors:
        - class: Fillna
          kwargs:
              fields_group: feature
        - class: CSZScoreNorm
          kwargs:
              fields_group: feature
    learn_processors:
        - class: DropnaLabel
        - class: CSZScoreNorm
          kwargs:
              fields_group: label

task:
    model:
        class: LGBModel
        module_path: qlib.contrib.model.gbdt
        kwargs:
            loss: mse
            learning_rate: 0.05
            num_leaves: 16
            max_depth: 4
            n_estimators: 20
            num_threads: 2
    dataset:
        class: DatasetH
        module_path: qlib.data.dataset
        kwargs:
            handler:
                class: DataHandlerLP
                module_path: qlib.contrib.data.handler
                kwargs: *data_handler_config
            segments:
                train: [2020-01-01, 2020-01-31]
                valid: [2020-02-01, 2020-02-28]
                test: [2020-03-01, 2020-03-31]
    record:
        - class: SignalRecord
          module_path: qlib.workflow.record_temp
          kwargs:
              model: <MODEL>
              dataset: <DATASET>
        - class: SigAnaRecord
          module_path: qlib.workflow.record_temp
          kwargs:
              ana_long_short: False
              ann_scaler: 252

